name: External Events
on:
  repository_dispatch:
    types: [build]
  workflow_dispatch:
  
jobs:
  echo-a-string:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.client_payload.env }}