name: Go CI/CD

on:
  push:
    branches:
      - main  # Replace 'main' with your default branch name

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'  # Replace with your desired Go version

    - name: Build
      run: go build ./...

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'  # Replace with your desired Go version

    - name: Test
      run: go test ./...

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build, test]  # Wait for the build and test jobs to complete

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy
      run: |
        # Add your deployment commands here